runners:
  - name: oracle-runner
    cloud: oracle
    instance_type: VM.Standard2.1
    machine_image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaahkd2r3ecaf6kcsvv34aoetojhhrddp4kvffmkb33t4eyscnc24ua
    region: eu-frankfurt-1
    labels:
      - oracle