name: freesurfer

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths:
      - recipes/freesurfer/*
      - .github/workflows/freesurfer.yml
    branches:
      - master

env:
  GH_REGISTRY: ${{ secrets.GH_REGISTRY }}
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}
  OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
  OS_PROJECT_ID: ${{ secrets.SWIFT_OS_PROJECT_ID }}
  OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_SECRET }}

jobs:
  build-docker:
    runs-on: self-hosted
    outputs:
      BUILDDATE: ${{ steps.ENVVARS.outputs.BUILDDATE }}
      IMAGELIST: ${{ steps.IMAGEVARS.outputs.IMAGELIST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        id: ENVVARS
        run: |
          APPLICATION=$(basename $GITHUB_WORKFLOW .yml)
          SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
          BUILDDATE=`date +%Y%m%d`
          echo "APPLICATION=$APPLICATION" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
          echo "::set-output name=BUILDDATE::$BUILDDATE"
      - uses: actions/checkout@v2
      - name : Build recipes
        run: |
          echo "APPLICATION: $APPLICATION"
          cd recipes/$APPLICATION
          /bin/bash build.sh

      - name: Set image variables
        id: IMAGEVARS
        run: |
          IMAGELIST=()
          for DOCKERFILE in recipes/$APPLICATION/*.Dockerfile; do
            IMAGENAME=$(echo $(basename $DOCKERFILE .Dockerfile) | tr '[A-Z]' '[a-z]')
            echo "IMAGENAME: $IMAGENAME"
            echo "test command: bash /neurocommand/local/fetch_and_run.sh ${IMAGENAME//_/ } $BUILDDATE"
            IMAGELIST+=$IMAGENAME
          done
          echo "IMAGELIST=$IMAGELIST" >> $GITHUB_ENV
          echo "::set-output name=IMAGELIST::$IMAGELIST"
      - name: Log into Github Package registry
        if: env.GH_REGISTRY != ''
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Log into Dockerhub (optional)
        if: env.DOCKERHUB_ORG != ''
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name : Run docker builder + Upload to docker and github registry
        run: for IMAGENAME in "${IMAGELIST[@]}"; do /bin/bash .github/workflows/build-docker.sh $IMAGENAME; done
      - name: Generate job output
        run: |
          echo "The container has been successfully build. To test the container, run this:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          for IMAGENAME in "${IMAGELIST[@]}"; do echo "bash /neurocommand/local/fetch_and_run.sh ${IMAGENAME//_/ } $BUILDDATE" >> $GITHUB_STEP_SUMMARY; done